### ISSUE TITLE
初回ログイン後の操作手順の紹介を実装

### ISSUE THREAD

**Issue by ASO1701002** [ASO1701001/medice-note#101]
初回ログイン時に何をしていいかがわからない問題の改善 #63

上記のissueの追加改善。
初回ログイン後、何が出来るのかが未だに分かりづらい仕様なため、
機能の紹介やおすすめ利用手順をモーダルで表示する。

簡単なイメージはdiscord 一般 11/26 11:51 の動画を参考に。
このままでは画像の内容が非常に見えづらいので、モーダルのサイズの調整や、テキストによる簡単な内容の説明も追加する。

また、使い方のページに、チュートリアルを再度表示するボタン等を設置する。

**Comment by ASO1701001** [comment]
サンプルイメージ
![1](https://user-images.githubusercontent.com/44828085/100415050-919f7c80-30be-11eb-8584-96d72b4975ec.png)
![2](https://user-images.githubusercontent.com/44828085/100415056-95330380-30be-11eb-966b-1e8484f3eb3f.png)
![3](https://user-images.githubusercontent.com/44828085/100415057-95cb9a00-30be-11eb-862c-1093cbc75c21.png)

**Comment by 1701024** [comment]
#126

**Comment by ASO1701001** [comment]
`master`にマージし、リリースしました
