### ISSUE TITLE
イベントトラッキングの設定

### ISSUE THREAD

**Issue by ASO1701002** [ASO1701001/medice-note#115]

**Comment by ASO1701002** [comment]
Add event tracking #118

**Comment by ASO1701001** [comment]
`fix_format`ブランチにマージしました
一旦こっちで作業するので、このIssueはそのままにしてください

**Comment by ASO1701001** [comment]
`master_dev`にマージしました
~~12月18日~~ 12月17日の改善リリース時に公開します
