### ISSUE TITLE
薬情報のまとめて登録を実装

### ISSUE THREAD

**Issue by ASO1701001** [ASO1701001/medice-note#41]
薬を複数登録したい場合、現在の仕様では不便であるためまとめて登録を実装する

**Comment by ASO1701024** [comment]
![webdesign](https://user-images.githubusercontent.com/44828010/95829637-762c1c80-0d71-11eb-80a2-c3d94e8d0576.png)
画面レイアウト

**Comment by ASO1701024** [comment]
![1920 Web – 1@2x](https://user-images.githubusercontent.com/44828010/96394054-06e47b80-11fc-11eb-814a-e6a7ff08b7a7.png)
送信ボタンは必要なければ削除してください

**Comment by ASO1701024** [comment]
![Uploading 1920 Web – 1@2x.png…]()

**Comment by ASO1701001** [comment]
#43 と同時に対応
