### ISSUE TITLE
文字認識機能の追加

### ISSUE THREAD

**Issue by ASO1701024** [ASO1701001/medice-note#43]
文字認識による、自動入力機能

**Comment by ASO1701024** [comment]
![webdesign](https://user-images.githubusercontent.com/44828010/95820194-9d2f2200-0d62-11eb-86c5-172f3edcdba5.png)
画面レイアウト

**Comment by ASO1701002** [comment]
![Uploading アクティビティ図.png…]()

**Comment by ASO1701002** [comment]
Fix activity figure
![アクティビティ図0 2](https://user-images.githubusercontent.com/44827981/96220163-2fcdfc00-0fc3-11eb-93b7-5519074a8230.png)

**Comment by ASO1701002** [comment]
![1920_Web_12x](https://user-images.githubusercontent.com/44827981/96543070-86e31200-12de-11eb-84b4-84a2a6f652cd.png)
add display image

**Comment by ASO1701001** [comment]
#41 薬情報のまとめて登録を実装 と同時に対応

**Comment by ASO1701001** [comment]
#80 で`master_dev`に統合します

**Comment by ASO1701001** [comment]
文字列の類似度を判定するため、`jaro-winkler`を追加
https://github.com/jordanthomas/jaro-winkler

**Comment by ASO1701001** [comment]
#57 病院名・薬局名のオートコンプリート改善 と同時に対応

**Comment by ASO1701001** [comment]
文字列の類似度を判定するため、`jaro-winkler`を追加
https://github.com/jordanthomas/jaro-winkler

#57 病院名・薬局名のオートコンプリート改善 と同時に対応
2,450件から87,969件に向上しました

#80 で`master_dev`に統合します
