### ISSUE TITLE
初回ログイン時に何をしていいかがわからない問題の改善

### ISSUE THREAD

**Issue by ASO1701024** [ASO1701001/medice-note#63]
優先度１
改善内容　操作方法ページ作成
アプリケーションの操作方法がわからない(特に、初回ログイン後に何をすればいいのか)
まず、操作方法のページがあることを知ってもらうために、メールアドレス認証後に操作方法の説明に移るかどうかの選択画面を表示する。
最初に行う操作、アプリケーションの機能についての説明を記載する。

**Comment by ASO1701001** [comment]
#97 で`master_dev`にマージしました
11月27日の改善リリース時に公開します
