### ISSUE TITLE
薬情報登録ページの入力項目のレイアウト改善

### ISSUE THREAD

**Issue by ASO1701024** [ASO1701001/medice-note#65]
優先度３
改善内容 薬情報登録ページの入力項目のレイアウトの変更を行う。
PC向けのレイアウト変更
左の列(薬の名前、病院名、飲む個数、飲む時間)
右の列(処方日、処方期間、種類、グループ)
オプション(デフォルトでは隠す)、薬画像、説明
最後に登録ボタン

**Comment by ASO1701024** [comment]
<img width="948" alt="スクリーンショット 2020-11-25 11 58 43" src="https://user-images.githubusercontent.com/44828010/100181508-c58f6c00-2f1d-11eb-8a83-a8801eb6bd49.png">
レイアウト変更イメージ

**Comment by 1701024** [comment]
#98

**Comment by ASO1701001** [comment]
#104 で再度修正し`master_dev`にマージしました
12月4日の改善リリース時に公開します
