### ISSUE TITLE
複数入力できる項目が分かりにくい問題の改善

### ISSUE THREAD

**Issue by ASO1701024** [ASO1701001/medice-note#66]
優先度4
改善内容 複数入力または選択できる項目が分かりにくいので分かりやすくする。
例(色を変える、入力項目名の横に複数入力可と記載)

**Comment by ASO1701002** [comment]
dd annotation message #84

**Comment by ASO1701001** [comment]
`master_dev`にマージしました
11月13日の改善リリース時に公開します

**Comment by ASO1701002** [comment]
add annotation message again #86

他にも複数登録可の項目があったため、追加でプルリクエストを掛けています。

**Comment by ASO1701001** [comment]
`master_dev`にマージしました
11月13日の改善リリース時に公開します
