### ISSUE TITLE
リンクだと分かりにくい問題の改善

### ISSUE THREAD

**Issue by ASO1701024** [ASO1701001/medice-note#67]
優先度5
改善内容 リンクになっているところがわかりづらいので改善する。
例 リンクをボタン化

**Comment by 1701024** [comment]
薬情報一覧などのaタグが複数ある場合に、全てボタン化してしまうとレイアウトが複雑化してしまうためアカウント設定のアカウント削除のaタグのみボタン化。

**Comment by 1701024** [comment]
![image](https://user-images.githubusercontent.com/69281191/100831918-11a45880-34aa-11eb-8eb4-5e3e2e325201.png)

**Comment by 1701024** [comment]
#107

**Comment by ASO1701001** [comment]
マージしないため、クローズします
