### ISSUE TITLE
薬情報登録のグループ選択問題の改善

### ISSUE THREAD

**Issue by ASO1701024** [ASO1701001/medice-note#68]
優先度６
改善内容 選択していたグループページから薬情報登録ページに遷移した際に、選択していたグループを選択項目グループの初期値として設定できるようにする。
現在初期値がデフォルトになっているので、どのページから遷移してきたかを判定し、適切な情報を初期値に設定する。

**Comment by ASO1701002** [comment]
update bulk-group-update #82

**Comment by ASO1701001** [comment]
`master_dev`にマージしました
11月13日の改善リリース時に公開します
