### ISSUE TITLE
お薬カレンダーのサイズ改善

### ISSUE THREAD

**Issue by ASO1701024** [ASO1701001/medice-note#72]
優先度 低
改善内容 お薬カレンダーのサイズが大きくページをスクロールする必要があるので、１ページに収めるためにサイズを小さくする。

**Comment by ASO1701002** [comment]
resize medicine-calendar #94

**Comment by ASO1701002** [comment]
多少はどうしてもスクロール必要だけど、カレンダー機能部分は１画面に収まる程度に調整してます。

ウィンドウサイズ変更時に再度サイズを調整するなら、以下のコードを、fullCalendar生成時の連想配列に追加。
    windowResize: function () {
        $('#medicine-calendar').fullCalendar('option', 'height', window.innerHeight - 70);
    },

**Comment by ASO1701002** [comment]
この関数を入れてると画面サイズを小さくして使いたい時に不便だから、とりあえず消してます。

**Comment by ASO1701001** [comment]
`master_dev`にマージしました
11月20日の改善リリース時に公開します
