### ISSUE TITLE
お薬カレンダーの現在の日付、土日のカラー改善

### ISSUE THREAD

**Issue by ASO1701024** [ASO1701001/medice-note#73]
優先度 低
改善内容 お薬カレンダーで現在の日付、土日の日付がわかりにくいので、わかりやすくするためにバックグラウンドカラーを変更する。

**Comment by ASO1701002** [comment]
over ride medicine-calendar UI #92

**Comment by ASO1701001** [comment]
`master_dev`にマージしました
11月20日の改善リリース時に公開します
