### ISSUE TITLE
お薬カレンダーの空白の改善

### ISSUE THREAD

**Issue by ASO1701024** [ASO1701001/medice-note#74]
優先度 低
改善内容 お薬カレンダーに表示される薬が同じ日付に複数ある場合に1つ目と2つ目の間に空白が入るので、その空白が挿入されないようにする。

**Comment by ASO1701002** [comment]
over ride medicine-calendar UI #92
上記で直したつもりだったけど、今試したらうまく動かないので、ちょっと確認します。
キャッシュが悪さしてるのかも。

**Comment by ASO1701001** [comment]
`master_dev`にマージしました
11月20日の改善リリース時に公開します
