### ISSUE TITLE
Twitter・Facebookのリンク改善

### ISSUE THREAD

**Issue by ASO1701024** [ASO1701001/medice-note#75]
優先度 低(広告の集客効果により作業内容が変更)
改善内容 広告での集客が成功した場合、リンクを削除する。
成功しなかった場合、リンクを一番上に変更する。

**Comment by ASO1701002** [comment]
<div class="footer-right">
                    <a href="https://twitter.com/medice_note" class="mr-2" target="_blank" rel="noopener">
                        <i class="fab fa-fw fa-twitter mr-1"></i>@medice_note
                    </a>
                    <a href="https://www.facebook.com/medicenote/" target="_blank" rel="noopener">
                        <i class="fab fa-fw fa-facebook mr-1"></i>@medicenote
                    </a>
                </div>
戻す場合、上記のコードをbase.ejsのfooter内に再配置
詳細はプルリクエスト内の修正箇所を参照

**Comment by ASO1701002** [comment]
delete SNS icon #95

**Comment by ASO1701001** [comment]
`master_dev`にマージしました
11月20日の改善リリース時に公開します
