### ISSUE TITLE
HTMLメールの実装

### ISSUE THREAD

**Issue by ASO1701002** [ASO1701001/medice-note#89]
・アカウント登録
・2段階認証
以上のメールに反映させる。

**Comment by ASO1701001** [comment]
・アカウント登録時のメールアドレス認証
<img width="1568" alt="スクリーンショット 2020-11-16 14 29 21" src="https://user-images.githubusercontent.com/44828085/99216218-79a33f80-2818-11eb-8b71-887bba9c1905.png">
・パスワード再発行時のメールアドレス認証
<img width="1569" alt="スクリーンショット 2020-11-16 14 30 10" src="https://user-images.githubusercontent.com/44828085/99216227-7dcf5d00-2818-11eb-8bd6-3cc414ef60bf.png">
・ログイン時の2段階認証
<img width="1567" alt="スクリーンショット 2020-11-16 14 30 31" src="https://user-images.githubusercontent.com/44828085/99216232-82941100-2818-11eb-93a8-d19407711032.png">

以上3箇所をHTMLメールに移行する予定

**Comment by ASO1701001** [comment]
・アカウント登録時のメールアドレス認証（Android版Gmail）
![Screenshot_2020-11-17-11-48-47-688_com google android gm](https://user-images.githubusercontent.com/44828085/99341157-b16bbf00-28cc-11eb-9b0e-a199dec72ca4.png)
・パスワード再発行時のメールアドレス認証（Android版Gmail）
![Screenshot_2020-11-17-11-49-26-381_com google android gm](https://user-images.githubusercontent.com/44828085/99341161-b4ff4600-28cc-11eb-9708-f5f3cf20e942.png)
・ログイン時の2段階認証（Android版Gmail）
![Screenshot_2020-11-17-11-49-44-658_com google android gm](https://user-images.githubusercontent.com/44828085/99341166-b7fa3680-28cc-11eb-8053-0019d53bc638.png)

**Comment by ASO1701001** [comment]
Handlebars.js
https://github.com/handlebars-lang/handlebars.js

#90 HTMLメール 実装 `master_dev`にマージ
